/// <summary>
/// XML documentation comments are allowed
/// </summary>
public class InvoiceCalculator
{
    // <auto-generated>
    public decimal Calculate(decimal amount)
    {
        // ruleid: csharp-no-comments
        // add 20 percent VAT
        decimal vat = 0.20m;

        // ruleid: csharp-no-comments
        /* multi-line comment */
        return amount + (amount * vat);
    }

    public decimal SafeMethod(decimal price)
    {
        // ok: csharp-no-comments
        // <auto-generated>
        return price;
    }
}
